

"use client";

import React, { useState, useEffect, useRef } from 'react';
import Waveform from './Waveform';
import { 
  Mic, 
  MicOff, 
  CheckCircle2, 
  Radio, 
  Loader2, 
  Globe, 
  Send, 
  Volume2, 
  Bot, 
  ArrowRight, 
  MessageSquare, 
  Circle,
  Wrench,
  Users,
  Award,
  Sparkles,
  ChevronRight
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toaster } from '@/components/ui/toaster';
import { Stepper, StepItem } from '@/components/ui/Stepper';
import TalkingHeadAvatar from './TalkingHeadAvatar';

interface VoiceArenaProps {
  questions?: any[];
  onFinish?: () => void;
}

const SUPPORTED_LANGUAGES = [
  { code: "en-IN", name: "English (India)" },
  { code: "hi-IN", name: "Hindi (हिंदी)" },
  { code: "ta-IN", name: "Tamil (தமிழ்)" },
  { code: "te-IN", name: "Telugu (తెలుగు)" },
  { code: "kn-IN", name: "Kannada (ಕನ್ನಡ)" },
  { code: "ml-IN", name: "Malayalam (മലയാളം)" },
  { code: "mr-IN", name: "Marathi (मराठी)" },
  { code: "bn-IN", name: "Bengali (বাংলা)" },
  { code: "gu-IN", name: "Gujarati (ગુજરાતી)" },
  { code: "pa-IN", name: "Punjabi (ਪੰਜਾਬੀ)" },
];

const roundLabels: Record<string, string> = {
  technical: "Technical Viva Round",
  behavioral: "Behavioral Interview",
  cultural: "Cultural Fit & Values"
};

const roundIcons: Record<string, any> = {
  technical: Wrench,
  behavioral: Users,
  cultural: Award
};

const VoiceArena = ({ questions = [], onFinish }: VoiceArenaProps) => {
  const [isAiSpeaking, setIsAiSpeaking] = useState(false);
  const [isConnecting, setIsConnecting] = useState(false);
  const [transcript, setTranscript] = useState<{ role: 'ai' | 'user', text: string }[]>([]);
  const [isListening, setIsListening] = useState(false);
  const [selectedLanguage, setSelectedLanguage] = useState("en-IN");
  const [userInputText, setUserInputText] = useState("");
  const [isProcessingTurn, setIsProcessingTurn] = useState(false);

  const audioRef = useRef<HTMLAudioElement | null>(null);
  const recognitionRef = useRef<any>(null);
  const mounted = useRef(true);
  const initialized = useRef(false);

  const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:5000";

  // Derive available unique rounds from questions
  const availableRounds: Array<'technical' | 'behavioral' | 'cultural'> = React.useMemo(() => {
    const extracted = Array.from(new Set(questions.map(q => q.round).filter(Boolean)));
    return extracted.length > 0 ? (extracted as any) : ['technical', 'behavioral', 'cultural'];
  }, [questions]);

  const [currentRoundIdx, setCurrentRoundIdx] = useState(0);
  const activeRound = availableRounds[currentRoundIdx] || 'technical';

  // Filter questions for the current active round
  const currentRoundQuestions = questions.filter(q => !q.round || q.round === activeRound);
  const activeQuestionsList = currentRoundQuestions.length > 0 ? currentRoundQuestions : questions;

  const latestAiSpeechText = transcript.slice().reverse().find(t => t.role === 'ai')?.text || activeQuestionsList[0]?.question || "Hello! Welcome to your mock interview session.";

  // Play audio from base64 string generated by Sarvam TTS (Bulbul v3)
  const playAudioBase64 = (base64Audio: string) => {
    try {
      if (audioRef.current) {
        audioRef.current.pause();
      }
      const audioUrl = `data:audio/wav;base64,${base64Audio}`;
      const audio = new Audio(audioUrl);
      audioRef.current = audio;

      audio.onplay = () => {
        if (mounted.current) setIsAiSpeaking(true);
      };
      audio.onended = () => {
        if (mounted.current) setIsAiSpeaking(false);
      };
      audio.onerror = (e) => {
        console.error("Audio playback error:", e);
        if (mounted.current) setIsAiSpeaking(false);
      };

      audio.play().catch(err => {
        console.warn("Autoplay prevented:", err);
        if (mounted.current) setIsAiSpeaking(false);
      });
    } catch (err) {
      console.error("Failed to play Sarvam audio:", err);
      if (mounted.current) setIsAiSpeaking(false);
    }
  };

  // Process turn with Sarvam AI (sarvam-105b + Bulbul v3 TTS)
  const sendCandidateTurn = async (candidateText: string) => {
    if (!candidateText.trim() || isProcessingTurn) return;

    setIsProcessingTurn(true);
    setUserInputText("");

    // Add candidate message to transcript
    const userMsg = { role: 'user' as const, text: candidateText };
    setTranscript(prev => [...prev, userMsg]);

    try {
      const response = await fetch(`${BACKEND_URL}/api/sarvam/voice-turn`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          candidateTranscript: candidateText,
          questions: activeQuestionsList,
          conversationHistory: [...transcript, userMsg],
          languageCode: selectedLanguage,
          activeRound: activeRound,
        }),
      });

      const text = await response.text();
      let data: any = {};
      try {
        data = JSON.parse(text);
      } catch (e) {
        throw new Error(`Server returned Non-JSON response (${response.status})`);
      }

      if (!response.ok || !data.success) {
        throw new Error(data.error || "Failed to process voice turn");
      }

      // Add AI response to transcript
      const aiMsg = { role: 'ai' as const, text: data.aiResponse };
      setTranscript(prev => [...prev, aiMsg]);

      // Play Sarvam TTS Audio
      if (data.audioBase64) {
        playAudioBase64(data.audioBase64);
      }
    } catch (error: any) {
      console.error("Sarvam Voice Turn Error:", error);
      toaster.create({
        title: "Voice Response Error",
        description: error.message || "Failed to generate AI recruiter voice response.",
        type: "error",
      });
    } finally {
      if (mounted.current) setIsProcessingTurn(false);
    }
  };

  // Transition to Next Round automatically with Sarvam AI Voice announcement
  const handleNextRound = async () => {
    if (currentRoundIdx < availableRounds.length - 1) {
      const nextIdx = currentRoundIdx + 1;
      const nextRound = availableRounds[nextIdx];
      setCurrentRoundIdx(nextIdx);

      const announcementText = `Great job completing the ${roundLabels[activeRound]}! We are now starting Stage ${nextIdx + 1}: ${roundLabels[nextRound]}. Let's continue.`;

      // Add AI transition message to transcript
      setTranscript(prev => [...prev, { role: 'ai', text: announcementText }]);

      // Play Sarvam TTS Audio for transition
      try {
        const response = await fetch(`${BACKEND_URL}/api/sarvam/tts`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            text: announcementText,
            languageCode: selectedLanguage,
            speaker: "ritu",
          }),
        });
        const resText = await response.text();
        let data: any = {};
        try { data = JSON.parse(resText); } catch (e) {}
        if (data.success && data.audioBase64) {
          playAudioBase64(data.audioBase64);
        }
      } catch (err) {
        console.warn("Round transition TTS error:", err);
      }

      toaster.create({
        title: `Stage ${nextIdx + 1} Started`,
        description: `Now conducting ${roundLabels[nextRound]}`,
        type: "info"
      });
    } else {
      handleFinish();
    }
  };

  // Initial welcome greeting from Sarvam AI
  useEffect(() => {
    mounted.current = true;

    if (initialized.current) return;
    initialized.current = true;

    const startSarvamWelcome = async () => {
      setIsConnecting(true);
      try {
        const welcomeText = `Welcome to your mock interview. We are starting with Stage 1: ${roundLabels[activeRound]}. Are you ready to begin?`;
        
        const response = await fetch(`${BACKEND_URL}/api/sarvam/tts`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            text: welcomeText,
            languageCode: selectedLanguage,
            speaker: "ritu",
          }),
        });

        const resText = await response.text();
        let data: any = {};
        try { data = JSON.parse(resText); } catch (e) {}

        if (mounted.current) {
          setTranscript([{ role: 'ai', text: welcomeText }]);
          if (data.success && data.audioBase64) {
            playAudioBase64(data.audioBase64);
          }
        }
      } catch (err) {
        console.warn("Welcome TTS failed, fallback to text:", err);
      } finally {
        if (mounted.current) setIsConnecting(false);
      }
    };

    startSarvamWelcome();

    return () => {
      mounted.current = false;
      if (audioRef.current) audioRef.current.pause();
      if (recognitionRef.current) {
        try { recognitionRef.current.stop(); } catch (e) {}
      }
    };
  }, []);

  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const audioChunksRef = useRef<Blob[]>([]);
  const recTimeoutRef = useRef<any>(null);

  const stopMediaRecording = () => {
    if (recTimeoutRef.current) clearTimeout(recTimeoutRef.current);
    if (mediaRecorderRef.current && mediaRecorderRef.current.state === "recording") {
      mediaRecorderRef.current.stop();
    }
  };

  const startMediaRecording = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const mediaRecorder = new MediaRecorder(stream);
      mediaRecorderRef.current = mediaRecorder;
      audioChunksRef.current = [];

      mediaRecorder.ondataavailable = (event) => {
        if (event.data.size > 0) {
          audioChunksRef.current.push(event.data);
        }
      };

      mediaRecorder.onstop = async () => {
        if (recTimeoutRef.current) clearTimeout(recTimeoutRef.current);
        const audioBlob = new Blob(audioChunksRef.current, { type: 'audio/wav' });
        stream.getTracks().forEach(track => track.stop());

        const reader = new FileReader();
        reader.readAsDataURL(audioBlob);
        reader.onloadend = async () => {
          const base64Audio = (reader.result as string).split(',')[1];
          if (!base64Audio) return;

          try {
            setIsProcessingTurn(true);
            const res = await fetch(`${BACKEND_URL}/api/sarvam/stt`, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                audioBase64: base64Audio,
                languageCode: selectedLanguage,
              })
            });
            const data = await res.json();
            if (data.success && data.transcript) {
              sendCandidateTurn(data.transcript);
            }
          } catch (e) {
            console.error("Sarvam STT fallback error:", e);
          } finally {
            if (mounted.current) setIsProcessingTurn(false);
          }
        };
      };

      mediaRecorder.start();
      if (mounted.current) setIsListening(true);

      // Auto-stop recording at 24 seconds (Sarvam single audio STT 30s limit)
      recTimeoutRef.current = setTimeout(() => {
        if (mediaRecorderRef.current && mediaRecorderRef.current.state === "recording") {
          toaster.create({
            title: "24s Speech Limit Reached",
            description: "Processing your audio turn...",
            type: "info"
          });
          stopMediaRecording();
        }
      }, 24000);
    } catch (err) {
      console.error("MediaRecorder microphone permission error:", err);
      toaster.create({
        title: "Microphone Access Error",
        description: "Please allow microphone access or type your response below.",
        type: "error"
      });
      if (mounted.current) setIsListening(false);
    }
  };

  // Web Speech API Multilingual Speech Recognition
  const startListening = () => {
    if (!('webkitSpeechRecognition' in window || 'SpeechRecognition' in window)) {
      startMediaRecording();
      return;
    }

    try {
      const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
      const recognition = new SpeechRecognition();
      recognitionRef.current = recognition;

      recognition.continuous = false;
      recognition.interimResults = false;
      recognition.lang = selectedLanguage;

      recognition.onstart = () => {
        if (mounted.current) setIsListening(true);
      };

      recognition.onresult = (event: any) => {
        const text = event.results[0][0].transcript;
        if (text && mounted.current) {
          sendCandidateTurn(text);
        }
      };

      recognition.onerror = (event: any) => {
        console.warn("Speech Recognition Event:", event.error);
        if (event.error === 'network' || event.error === 'no-speech' || event.error === 'audio-capture' || event.error === 'not-allowed') {
          console.log("Switching to direct Sarvam STT MediaRecorder fallback...");
          startMediaRecording();
        } else if (mounted.current) {
          setIsListening(false);
        }
      };

      recognition.onend = () => {
        if (mounted.current && !mediaRecorderRef.current) setIsListening(false);
      };

      recognition.start();
    } catch (err) {
      console.warn("Speech recognition failed to start, falling back to Sarvam STT:", err);
      startMediaRecording();
    }
  };

  const stopListening = () => {
    if (recognitionRef.current) {
      try {
        recognitionRef.current.stop();
      } catch (e) {}
    }
    stopMediaRecording();
    setIsListening(false);
  };

  const handleToggleMic = () => {
    if (isListening) {
      stopListening();
    } else {
      startListening();
    }
  };

  const handleFinish = () => {
    if (audioRef.current) audioRef.current.pause();
    if (recognitionRef.current) {
      try { recognitionRef.current.stop(); } catch (e) {}
    }
    if (onFinish) {
      onFinish();
    }
  };

  const ActiveIcon = roundIcons[activeRound] || Wrench;

  return (
    <div className="min-h-[calc(100vh-64px)] bg-slate-50 text-slate-900 px-4 py-6 sm:px-6 lg:px-10 font-sans">
      <div className="max-w-6xl mx-auto space-y-6">
        
        {/* Minimal Header & Sequential Stepper */}
        <header className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-1">
            <div className="flex items-center gap-2 text-xs font-semibold text-slate-500 uppercase tracking-wider">
              <span>Sarvam Voice Interview</span>
              <span>•</span>
              <span className="text-orange-600 font-bold">Stage {currentRoundIdx + 1} of {availableRounds.length}</span>
            </div>
            <h1 className="text-2xl font-bold tracking-tight text-slate-900 flex items-center gap-2">
              <ActiveIcon className="w-6 h-6 text-orange-600" />
              {roundLabels[activeRound]}
            </h1>
          </div>

          {/* Sequential Stepper (ReactBits 3-Color Minimalist Pattern) */}
          <div className="max-w-md w-full">
            <Stepper
              steps={availableRounds.map(r => ({
                id: r,
                title: roundLabels[r],
                description: r === 'technical' ? 'Technical Viva' : r === 'behavioral' ? 'STAR Method' : 'Culture Fit'
              }))}
              currentStep={currentRoundIdx}
            />
          </div>

          {/* Multilingual Selector */}
          <div className="flex items-center gap-2 bg-slate-50 border border-slate-200 px-3 py-2 rounded-xl text-xs font-semibold text-slate-700">
            <Globe className="w-4 h-4 text-slate-500" />
            <select
              value={selectedLanguage}
              onChange={(e) => setSelectedLanguage(e.target.value)}
              className="bg-transparent text-xs font-bold text-slate-900 outline-none cursor-pointer"
            >
              {SUPPORTED_LANGUAGES.map((lang) => (
                <option key={lang.code} value={lang.code}>
                  {lang.name}
                </option>
              ))}
            </select>
          </div>
        </header>

        {/* Main Grid */}
        <main className="grid grid-cols-1 lg:grid-cols-[1fr_1.1fr] gap-8">
          
          {/* LEFT: Recruiter Stage & Controls */}
          <section className="bg-white border border-slate-200 rounded-2xl p-8 shadow-sm flex flex-col justify-between min-h-130">
            
            {/* Status Bar */}
            <div className="flex items-center justify-between border-b border-slate-100 pb-4">
              <div className="flex items-center gap-2 text-xs font-semibold text-slate-700">
                <Circle className={`w-2.5 h-2.5 fill-current ${
                  isAiSpeaking ? 'text-orange-500' : isListening ? 'text-emerald-500' : 'text-slate-300'
                }`} />
                <span>
                  {isAiSpeaking ? 'Recruiter Speaking' : isListening ? 'Listening to Candidate' : 'Ready for response'}
                </span>
              </div>
              <span className="text-xs font-normal text-slate-400">Sarvam Multilingual Voice</span>
            </div>

            {/* 3D TalkingHead Realistic AI Recruiter Avatar Stage */}
            <div className="my-6 flex flex-col items-center justify-center text-center space-y-4">
              <TalkingHeadAvatar
                isAiSpeaking={isAiSpeaking}
                isListening={isListening}
                speechText={latestAiSpeechText}
                selectedLanguage={selectedLanguage}
              />
              <div className="space-y-1 pt-2">
                <h2 className="text-lg font-semibold text-slate-900">{roundLabels[activeRound]}</h2>
                <p className="text-xs text-slate-500 font-normal max-w-sm">
                  Speak into your microphone or type your answer below. Real-time 3D viseme lip-sync active.
                </p>
              </div>
            </div>

            {/* Controls Bar */}
            <div className="space-y-4 pt-6 border-t border-slate-100">
              <div className="flex items-center gap-3">
                <button
                  disabled={isConnecting || isProcessingTurn}
                  onClick={handleToggleMic}
                  className={`w-11 h-11 rounded-xl border flex items-center justify-center transition-colors ${
                    isListening
                      ? 'bg-red-600 border-red-600 text-white'
                      : 'bg-white border-slate-200 text-slate-700 hover:border-slate-300'
                  } disabled:opacity-40 disabled:cursor-not-allowed`}
                  title={isListening ? 'Stop Recording' : 'Start Mic'}
                >
                  {isListening ? <MicOff className="w-4 h-4" /> : <Mic className="w-4 h-4" />}
                </button>

                {/* Text Fallback Input */}
                <div className="flex-1 flex gap-2">
                  <input
                    type="text"
                    value={userInputText}
                    onChange={(e) => setUserInputText(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') sendCandidateTurn(userInputText);
                    }}
                    placeholder="Type your answer here..."
                    disabled={isProcessingTurn}
                    className="flex-1 bg-slate-50 border border-slate-200 rounded-xl px-4 text-xs font-medium text-slate-900 outline-none focus:border-slate-400"
                  />
                  <Button
                    disabled={!userInputText.trim() || isProcessingTurn}
                    onClick={() => sendCandidateTurn(userInputText)}
                    className="bg-slate-900 hover:bg-slate-800 text-white rounded-xl px-4"
                  >
                    {isProcessingTurn ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
                  </Button>
                </div>
              </div>

              {/* Action Button: Sequential Round Transition */}
              <Button
                disabled={isConnecting || isProcessingTurn}
                onClick={handleNextRound}
                className="w-full h-12 bg-orange-600 hover:bg-orange-700 text-white font-bold rounded-xl text-xs uppercase tracking-wider flex items-center justify-center gap-2 shadow-sm transition-all"
              >
                {currentRoundIdx < availableRounds.length - 1 ? (
                  <>
                    <CheckCircle2 className="w-4 h-4" />
                    Complete Round {currentRoundIdx + 1} & Start {roundLabels[availableRounds[currentRoundIdx + 1]]}
                    <ArrowRight className="w-4 h-4" />
                  </>
                ) : (
                  <>
                    <CheckCircle2 className="w-4 h-4" />
                    Complete Interview & View Results
                  </>
                )}
              </Button>
            </div>
          </section>

          {/* RIGHT: Live Conversation Transcript */}
          <section className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm flex flex-col justify-between min-h-135">
            <div className="flex items-center justify-between border-b border-slate-100 pb-4 mb-4">
              <div className="flex items-center gap-2">
                <MessageSquare className="w-4 h-4 text-orange-600" />
                <h2 className="text-sm font-bold text-slate-900">Live Interview Transcript</h2>
              </div>
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1">
                <Volume2 className="w-3 h-3 text-slate-400" /> Voice Active
              </span>
            </div>

            <div className="flex-1 overflow-y-auto space-y-4 pr-1 max-h-105 custom-scrollbar">
              {transcript.length === 0 && !isConnecting && (
                <div className="h-full flex flex-col items-center justify-center text-slate-400 space-y-2 py-12">
                  <Radio className="w-6 h-6 text-slate-300" />
                  <p className="text-xs font-semibold">Conversation transcript will appear here.</p>
                </div>
              )}

              {transcript.map((line, i) => (
                <div
                  key={i}
                  className={`flex ${line.role === 'ai' ? 'justify-start' : 'justify-end'}`}
                >
                  <div className={`max-w-[85%] rounded-2xl px-4 py-3 text-xs font-medium leading-relaxed ${
                    line.role === 'ai'
                      ? 'bg-slate-100 text-slate-800 rounded-tl-none border border-slate-200/50'
                      : 'bg-slate-900 text-white rounded-tr-none'
                  }`}>
                    <p className={`text-[10px] font-bold uppercase tracking-wider mb-1 ${
                      line.role === 'ai' ? 'text-orange-600' : 'text-slate-300'
                    }`}>
                      {line.role === 'ai' ? 'Sarvam AI Recruiter' : 'Candidate'}
                    </p>
                    {line.text}
                  </div>
                </div>
              ))}

              {isProcessingTurn && (
                <div className="flex items-center gap-2 text-xs font-semibold text-orange-600 py-2">
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Evaluating response...</span>
                </div>
              )}
            </div>
          </section>

        </main>
      </div>

      <style jsx>{`
        .custom-scrollbar::-webkit-scrollbar {
          width: 4px;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #cbd5e1;
          border-radius: 4px;
        }
      `}</style>
    </div>
  );
};

export default VoiceArena;
