"use client"

import Link from "next/link"
import { useCallback, useEffect, useMemo, useState } from "react"
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from "recharts"
import { ArrowRight, BriefcaseBusiness, CheckCircle2, ChevronRight, FileText, RefreshCw, Sparkles, Target, Zap } from "lucide-react"
import { DynamicNavbar } from "@/components/dynamic-navbar"
import { ProtectedRoute } from "@/components/protected-route"
import { useAuth } from "@/lib/auth-context"
import { getDashboardData, getSkills, type DashboardData, type Skill } from "@/lib/api"
import "./dashboard.css"

const fallbackChart = [{ m: "Feb", v: 28 }, { m: "Mar", v: 39 }, { m: "Apr", v: 35 }, { m: "May", v: 57 }, { m: "Jun", v: 53 }, { m: "Jul", v: 70 }, { m: "Aug", v: 78 }]

export default function DashboardPage() {
  const { user } = useAuth(); const [mounted, setMounted] = useState(false); const [loading, setLoading] = useState(true); const [data, setData] = useState<DashboardData | null>(null); const [skills, setSkills] = useState<Skill[]>([])
  const fetchData = useCallback(async () => { setLoading(true); const [dashboard, skillResult] = await Promise.all([getDashboardData(), getSkills()]); if (dashboard.data) setData(dashboard.data); if (skillResult.data?.skills) setSkills(skillResult.data.skills); setLoading(false) }, [])
  useEffect(() => setMounted(true), []); useEffect(() => { if (mounted) fetchData() }, [mounted, fetchData])
  const chart = useMemo(() => skills.length > 2 ? skills.slice(0, 7).map((skill) => ({ m: skill.skill_name.slice(0, 4), v: skill.proficiency || 0 })) : fallbackChart, [skills])
  if (!mounted) return null
  const overview = data?.profile_overview; const career = data?.career_dashboard; const stats = data?.quick_stats; const profile = career?.profile_summary
  const name = data?.user_name?.split(" ")[0] || user?.name?.split(" ")[0] || "there"; const score = overview?.resume_score ?? 0; const readiness = profile?.profile_strength_score || overview?.completeness_percentage || 0
  const actions = career?.action_items?.slice(0, 3) || ["Build a sharper profile", "Create your targeted resume", "Explore your best-fit roles"]
  return <ProtectedRoute><div className="dashboard-theme min-h-screen"><DynamicNavbar /><main className="mx-auto max-w-[1240px] px-5 pb-16 pt-10 lg:px-8 lg:pt-14">
    <section className="mb-10 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-3 flex items-center gap-2 text-sm font-medium text-[#79736c]"><Sparkles className="size-4 text-[#ef4a18]" /> Your personal career space</p><h1 className="text-[clamp(2.65rem,5vw,4.5rem)] font-semibold leading-[.98] tracking-[-.065em] text-[#171716]">Welcome back, {name}.</h1><p className="mt-3 text-base text-[#6e6862]">Here’s where your next great opportunity starts.</p></div><button onClick={fetchData} disabled={loading} className="inline-flex w-fit items-center gap-2 rounded-full bg-[#ef4a18] px-5 py-3 text-sm font-semibold text-white shadow-[0_10px_24px_rgba(239,74,24,.22)] transition hover:-translate-y-0.5 hover:bg-[#d93d10]"><RefreshCw className={`size-4 ${loading ? "animate-spin" : ""}`} />Refresh insights</button></section>
    <section className="grid gap-5 lg:grid-cols-[1.35fr_.85fr]">
      <div className="relative overflow-hidden rounded-[28px] bg-[#181818] p-7 text-white sm:p-9"><div className="absolute -right-20 -top-20 size-72 rounded-full border-[28px] border-[#ef4a18]/90" /><div className="absolute -bottom-28 right-24 size-52 rounded-full bg-[#ff7348] blur-3xl opacity-30" /><div className="relative z-10 flex h-full min-h-[320px] flex-col"><span className="w-fit rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-medium text-white/80">Your focus for this week</span><h2 className="mt-7 max-w-lg text-3xl font-semibold leading-[1.03] tracking-[-.055em] sm:text-4xl">Turn your profile into a role-ready story.</h2><p className="mt-4 max-w-md text-sm leading-6 text-white/65">Your strongest route is clearer now. Complete one focused action and we’ll tailor the rest of your path around it.</p><Link href="/resume-builder" className="mt-auto inline-flex w-fit items-center gap-2 rounded-full bg-white px-5 py-3 text-sm font-semibold text-[#171716] transition hover:bg-[#ffe9e1]">Build my resume <ArrowRight className="size-4" /></Link></div></div>
      <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-1"><div className="rounded-[24px] border border-[#e8e1da] bg-white p-6"><div className="flex items-start justify-between"><div className="grid size-10 place-items-center rounded-xl bg-[#fff0eb] text-[#ef4a18]"><FileText className="size-5" /></div><span className="rounded-full bg-[#eaf6ee] px-2.5 py-1 text-xs font-semibold text-[#287443]">{overview?.has_resume ? "Active" : "Start here"}</span></div><p className="mt-7 text-xs font-semibold uppercase tracking-[.12em] text-[#8a837b]">Resume score</p><p className="mt-1 text-5xl font-semibold tracking-[-.07em] text-[#171716]">{score}<span className="ml-1 text-xl text-[#8a837b]">/100</span></p><p className="mt-2 text-sm text-[#746e67]">{score ? "ATS readiness is looking good." : "Upload a resume to unlock your score."}</p></div><div className="rounded-[24px] border border-[#e8e1da] bg-[#fff7f3] p-6"><div className="flex items-center justify-between"><div className="grid size-10 place-items-center rounded-xl bg-[#ef4a18] text-white"><Target className="size-5" /></div><span className="text-xs font-semibold text-[#ef4a18]">+{Math.max(readiness - 50, 0)}% this month</span></div><p className="mt-7 text-xs font-semibold uppercase tracking-[.12em] text-[#8a837b]">Career readiness</p><p className="mt-1 text-5xl font-semibold tracking-[-.07em] text-[#171716]">{readiness}<span className="ml-1 text-xl text-[#8a837b]">%</span></p><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#f0ddd4]"><div className="h-full rounded-full bg-[#ef4a18]" style={{ width: `${Math.min(readiness, 100)}%` }} /></div></div></div>
    </section>
    <section className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-[26px] border border-[#e8e1da] bg-white p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="flex items-center gap-2 text-sm font-semibold text-[#171716]"><span className="grid size-8 place-items-center rounded-lg bg-[#fff0eb] text-[#ef4a18]"><Zap className="size-4" /></span> Your next moves</p><p className="mt-3 text-sm text-[#77716b]">Small wins, carefully picked for your current direction.</p></div><Link href="/career-path" className="hidden text-sm font-semibold text-[#ef4a18] sm:block">View path</Link></div><div className="mt-6 space-y-3">{actions.map((action, index) => <Link href={index === 1 ? "/resume-builder" : index === 2 ? "/career-path" : "/profile"} key={action} className="group flex items-center gap-4 rounded-2xl border border-[#eee8e2] p-4 transition hover:border-[#ef4a18]/35 hover:bg-[#fffaf7]"><span className={`grid size-9 shrink-0 place-items-center rounded-full text-xs font-bold ${index === 0 ? "bg-[#ef4a18] text-white" : "bg-[#f4f1ed] text-[#6e6862]"}`}>0{index + 1}</span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-[#252321]">{action}</span><span className="mt-1 block text-xs text-[#807971]">{index === 0 ? "Best place to invest your attention" : index === 1 ? "Make every application count" : "Discover roles matched to you"}</span></span><ChevronRight className="size-5 text-[#b4aca4] transition group-hover:translate-x-1 group-hover:text-[#ef4a18]" /></Link>)}</div></div>
      <div className="rounded-[26px] border border-[#e8e1da] bg-white p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="flex items-center gap-2 text-sm font-semibold"><span className="grid size-8 place-items-center rounded-lg bg-[#fff0eb] text-[#ef4a18]"><BriefcaseBusiness className="size-4" /></span> Skills momentum</p><p className="mt-3 text-sm text-[#77716b]">Your strongest building blocks.</p></div><span className="text-sm font-semibold text-[#ef4a18]">{stats?.total_skills || skills.length} skills</span></div><div className="mt-5 h-40"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{ top: 14, right: 2, left: -20, bottom: 0 }}><defs><linearGradient id="orangeCurve" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ef4a18" stopOpacity=".3"/><stop offset="1" stopColor="#ef4a18" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="m" axisLine={false} tickLine={false} tick={{ fill: "#958d85", fontSize: 10 }} /><Tooltip cursor={false} contentStyle={{ border: "1px solid #eadfd7", borderRadius: 12, fontSize: 12 }} /><Area type="monotone" dataKey="v" stroke="#ef4a18" strokeWidth={2.5} fill="url(#orangeCurve)" /></AreaChart></ResponsiveContainer></div><div className="mt-4 rounded-xl bg-[#f8f5f1] p-3 text-xs leading-5 text-[#6e6862]"><CheckCircle2 className="mr-1.5 inline size-3.5 text-[#ef4a18]" />{profile?.primary_domain ? `${profile.primary_domain} is your clearest current signal.` : "Add your strengths to make this insight more precise."}</div></div></section>
    <section className="mt-10"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-2xl font-semibold tracking-[-.045em]">Built around you</h2><p className="mt-1 text-sm text-[#77716b]">A live read on the signals that matter.</p></div><Sparkles className="size-5 text-[#ef4a18]" /></div><div className="grid gap-4 md:grid-cols-3">{[["Your level", profile?.current_level || "Early career", "Your experience is shaping the right next step."], ["Profile strength", `${overview?.completeness_percentage || 0}% complete`, "A few details away from a sharper match."], ["Role direction", stats?.current_goal || "Exploring options", "Your path will get more tailored as you go."]].map(([label, value, copy]) => <div key={label} className="rounded-2xl border border-[#e8e1da] bg-white p-5 transition hover:-translate-y-1 hover:shadow-[0_14px_30px_rgba(81,54,42,.08)]"><p className="text-xs font-semibold uppercase tracking-[.12em] text-[#958d85]">{label}</p><p className="mt-5 text-xl font-semibold tracking-[-.04em] text-[#252321]">{value}</p><p className="mt-2 text-sm leading-6 text-[#77716b]">{copy}</p></div>)}</div></section>
  </main></div></ProtectedRoute>
}
