"use client"

import { useState } from "react"
import Image from "next/image"
import Link from "next/link"
import { usePathname, useRouter } from "next/navigation"
import { LogOut, Menu, MoreHorizontal, User, X } from "lucide-react"
import { useAuth } from "@/lib/auth-context"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import "@/app/dashboard/dashboard.css"

const primary = [{ label: "Dashboard", href: "/dashboard" }, { label: "System Design", href: "/system-design" }, { label: "Resume Arena", href: "/resume-arena" }, { label: "JD Match", href: "/match-analysis" }]
const secondary = [{ label: "Interview", href: "/interview" }, { label: "Opportunities", href: "/opportunities" }, { label: "Learning", href: "/ai-planner" }]

export function DynamicNavbar() {
  const pathname = usePathname(); const router = useRouter(); const { user, logout } = useAuth(); const [open, setOpen] = useState(false)
  const initials = user?.name?.split(" ").map((x) => x[0]).join("").slice(0, 2).toUpperCase() || "U"
  const item = (entry: { label: string; href: string }) => <Link key={entry.href} href={entry.href} className={`rounded-full px-4 py-2 text-sm font-medium transition-all ${pathname === entry.href ? "bg-[#ef4a18] text-white shadow-[0_6px_16px_rgba(239,74,24,.24)]" : "text-[#55524e] hover:bg-white hover:text-[#171716]"}`}>{entry.label}</Link>
  return <header className="niti-navigation sticky top-0 z-50 border-b border-black/[.04] bg-[#fcf9f5]/80 backdrop-blur-xl"><div className="mx-auto flex h-[88px] max-w-[1440px] items-center px-5 lg:px-8"><Link href="/dashboard" className="flex items-center gap-2"><Image src="/nitiai.png" alt="Niti AI" width={34} height={34} className="size-8 object-contain" /><span className="hidden text-[15px] font-semibold tracking-[-.045em] text-[#171716] sm:block">NitiAI</span></Link><nav className="absolute left-1/2 hidden -translate-x-1/2 items-center rounded-full bg-[#f3f0ec] p-1.5 lg:flex">{primary.map(item)}<DropdownMenu><DropdownMenuTrigger className="ml-1 flex size-9 items-center justify-center rounded-full text-[#55524e] hover:bg-white"><MoreHorizontal className="size-4" /></DropdownMenuTrigger><DropdownMenuContent className="mt-2 w-48 rounded-xl border-black/10 bg-white p-1.5" align="end">{secondary.map((entry) => <DropdownMenuItem asChild key={entry.href}><Link className="cursor-pointer rounded-lg px-3 py-2" href={entry.href}>{entry.label}</Link></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></nav><div className="ml-auto flex items-center gap-3"><button onClick={() => setOpen(!open)} className="grid size-10 place-items-center rounded-full bg-[#f3f0ec] lg:hidden">{open ? <X className="size-4" /> : <Menu className="size-4" />}</button><DropdownMenu><DropdownMenuTrigger asChild><button className="rounded-full outline-none ring-offset-2 focus-visible:ring-2 focus-visible:ring-[#ef4a18]"><Avatar className="size-9 border border-black/10"><AvatarImage src={user?.avatar || "/placeholder-user.jpg"} /><AvatarFallback className="bg-[#171716] text-[10px] text-white">{initials}</AvatarFallback></Avatar></button></DropdownMenuTrigger><DropdownMenuContent className="mr-2 w-56 rounded-xl border-black/10 bg-white" align="end"><DropdownMenuLabel className="font-normal"><p className="text-sm font-semibold">{user?.name || "Your account"}</p><p className="mt-1 text-xs text-[#77766f]">{user?.email}</p></DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuItem asChild><Link href="/profile" className="gap-2"><User className="size-4" />Profile</Link></DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem onClick={() => { logout(); router.push("/auth") }} className="gap-2 text-[#d53810]"><LogOut className="size-4" />Log out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></div>{open && <nav className="border-t border-black/[.06] bg-[#fcf9f5] px-5 py-3 lg:hidden"><div className="grid grid-cols-2 gap-2">{[...primary, ...secondary].map((entry) => <Link onClick={() => setOpen(false)} key={entry.href} href={entry.href} className={`rounded-xl px-4 py-3 text-sm font-medium ${pathname === entry.href ? "bg-[#ef4a18] text-white" : "bg-[#f3f0ec] text-[#55524e]"}`}>{entry.label}</Link>)}</div></nav>}</header>
}
